'use client';

// Pricer — a fast batch tool for pricing up talent. Paste a block of "Name<TAB>
// Price" rows copied straight from Excel / Google Sheets, and Pricer builds a
// table with four working columns:
//   1. Name   — pasted (editable: double-click)
//   2. Price  — pasted (editable: double-click)
//   3. Ticker — generated by DeepSeek (/api/ai/ticker): one word, 6–10 letters,
//               last-name-plus-initials or a clever play on the name. Editable.
//   4. Photo  — drag-and-drop an image onto the cell. It auto-crops to a centered
//               square; click the thumbnail to open the cropper and drag / zoom to
//               choose exactly what the square frames, then Done.
//
// Single-click a row to copy it (Name⇥Price⇥Ticker) to the clipboard — the fast
// path for pasting a finished row back into a sheet. Per-row ⬇ (or "Download all")
// exports the cropped photo as a PNG at full crop resolution, regardless of what
// format was dropped in.
//
// State persists to localStorage. Photos are kept as data URLs; if the batch is
// too large for the quota we fall back to persisting just the cropped thumbnails
// (the cells still render; full-res re-crop/download needs the originals, kept in
// memory for the session).

import React, { useCallback, useEffect, useRef, useState } from 'react';

// ── Types ────────────────────────────────────────────────────────────────────
interface Crop { sx: number; sy: number; size: number } // source-pixel square
interface ImgState {
  src: string;   // full-res original data URL ('' once evicted to fit the quota)
  nW: number; nH: number;
  crop: Crop;
  thumb: string; // small cropped square PNG data URL — what the cell shows
}
interface Row {
  id: string;
  name: string;
  price: string;
  ticker: string;
  img: ImgState | null;
}

const STORE_KEY = 'pricer.rows.v1';
const THUMB_PX = 240;

// ── Small helpers ──────────────────────────────────────────────────────────────
const newId = () => Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
const safeFile = (s: string) => (s || 'image').replace(/[^a-z0-9_-]+/gi, '_').replace(/^_+|_+$/g, '') || 'image';

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error('image load failed'));
    img.src = src;
  });
}
function fileToDataURL(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onload = () => resolve(String(r.result));
    r.onerror = () => reject(new Error('read failed'));
    r.readAsDataURL(file);
  });
}
async function cropToCanvas(src: string, crop: Crop, outSize: number): Promise<HTMLCanvasElement> {
  const img = await loadImage(src);
  const c = document.createElement('canvas');
  c.width = outSize; c.height = outSize;
  const ctx = c.getContext('2d')!;
  ctx.imageSmoothingQuality = 'high';
  ctx.drawImage(img, crop.sx, crop.sy, crop.size, crop.size, 0, 0, outSize, outSize);
  return c;
}
const cropToDataUrl = async (src: string, crop: Crop, out: number) =>
  (await cropToCanvas(src, crop, out)).toDataURL('image/png');
const cropToBlob = (src: string, crop: Crop, out: number): Promise<Blob> =>
  cropToCanvas(src, crop, out).then((c) => new Promise<Blob>((res) => c.toBlob((b) => res(b!), 'image/png')));

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// Parse a pasted Sheets/Excel block into {name, price} rows. Columns are split on
// TAB (how spreadsheets copy); falls back to peeling a trailing "$12.34"-style
// price token off a plain line.
function parsePaste(text: string): { name: string; price: string }[] {
  const out: { name: string; price: string }[] = [];
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line) continue;
    let name = line, price = '';
    if (line.includes('\t')) {
      const parts = line.split('\t').map((s) => s.trim());
      name = parts[0] ?? '';
      price = parts.slice(1).find((p) => /\d/.test(p)) ?? '';
    } else {
      const m = line.match(/^(.+?)[\s ]+(\$?\s*\d[\d.,]*)\s*$/);
      if (m) { name = m[1].trim(); price = m[2].replace(/\s+/g, ''); }
    }
    if (name) out.push({ name, price });
  }
  return out;
}

// ── Crop modal ─────────────────────────────────────────────────────────────────
// Square viewport; the image is shown at "cover or larger" scale and panned/zoomed
// so the user picks exactly what the square frames. Drag to pan, slider/wheel to
// zoom. On Done we hand back the source-pixel crop rect.
function CropModal({
  source, onDone, onCancel,
}: {
  source: { src: string; nW: number; nH: number; crop: Crop };
  onDone: (crop: Crop) => void;
  onCancel: () => void;
}) {
  const V = 380;
  const { src, nW, nH } = source;
  const baseScale = V / Math.min(nW, nH);              // "cover" scale (smaller side fills V)

  const initScale = V / source.crop.size;             // size = V / scale
  const initZoom = Math.max(1, initScale / baseScale);
  const [zoom, setZoom] = useState(initZoom);
  const [off, setOff] = useState(() => ({
    x: -source.crop.sx * (baseScale * initZoom),
    y: -source.crop.sy * (baseScale * initZoom),
  }));

  const vpRef = useRef<HTMLDivElement | null>(null);
  const drag = useRef<{ x: number; y: number; ox: number; oy: number } | null>(null);

  const scale = baseScale * zoom;
  const dispW = nW * scale, dispH = nH * scale;

  const clampOff = useCallback((o: { x: number; y: number }, s: number) => ({
    x: Math.min(0, Math.max(V - nW * s, o.x)),
    y: Math.min(0, Math.max(V - nH * s, o.y)),
  }), [nW, nH]);

  const applyZoom = useCallback((nextZoom: number) => {
    const nz = Math.min(10, Math.max(1, nextZoom));
    setZoom((curZoom) => {
      setOff((curOff) => {
        const oldS = baseScale * curZoom, newS = baseScale * nz;
        const cx = (V / 2 - curOff.x) / oldS;          // source point under viewport centre
        const cy = (V / 2 - curOff.y) / oldS;
        return clampOff({ x: V / 2 - cx * newS, y: V / 2 - cy * newS }, newS);
      });
      return nz;
    });
  }, [baseScale, clampOff]);

  // Non-passive wheel so we can zoom without scrolling the page.
  useEffect(() => {
    const el = vpRef.current;
    if (!el) return;
    const onWheel = (e: WheelEvent) => { e.preventDefault(); applyZoom(zoom * (e.deltaY < 0 ? 1.12 : 0.89)); };
    el.addEventListener('wheel', onWheel, { passive: false });
    return () => el.removeEventListener('wheel', onWheel);
  }, [zoom, applyZoom]);

  function onPointerDown(e: React.PointerEvent) {
    (e.currentTarget as Element).setPointerCapture(e.pointerId);
    drag.current = { x: e.clientX, y: e.clientY, ox: off.x, oy: off.y };
  }
  function onPointerMove(e: React.PointerEvent) {
    if (!drag.current) return;
    setOff(clampOff(
      { x: drag.current.ox + (e.clientX - drag.current.x), y: drag.current.oy + (e.clientY - drag.current.y) },
      scale,
    ));
  }
  const endDrag = () => { drag.current = null; };

  function done() {
    const size = V / scale;
    const sx = -off.x / scale, sy = -off.y / scale;
    const cs = Math.min(size, nW, nH);
    onDone({
      sx: Math.min(Math.max(0, sx), nW - cs),
      sy: Math.min(Math.max(0, sy), nH - cs),
      size: cs,
    });
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 backdrop-blur-sm"
      onClick={onCancel}
    >
      <div
        className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5 shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <p className="mb-3 text-center text-xs font-medium text-zinc-400">
          Drag to position · scroll or slide to zoom
        </p>
        <div
          ref={vpRef}
          className="relative overflow-hidden rounded-xl border border-zinc-700 bg-black cursor-grab active:cursor-grabbing select-none touch-none"
          style={{ width: V, height: V }}
          onPointerDown={onPointerDown}
          onPointerMove={onPointerMove}
          onPointerUp={endDrag}
          onPointerCancel={endDrag}
        >
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={src} alt="" draggable={false}
            style={{
              position: 'absolute', left: off.x, top: off.y, width: dispW, height: dispH,
              maxWidth: 'none', pointerEvents: 'none', userSelect: 'none',
            }}
          />
          {/* rule-of-thirds guide */}
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute inset-y-0 left-1/3 w-px bg-white/20" />
            <div className="absolute inset-y-0 left-2/3 w-px bg-white/20" />
            <div className="absolute inset-x-0 top-1/3 h-px bg-white/20" />
            <div className="absolute inset-x-0 top-2/3 h-px bg-white/20" />
          </div>
        </div>

        <div className="mt-4 flex items-center gap-3">
          <span className="text-[10px] text-zinc-500">Zoom</span>
          <input
            type="range" min={1} max={10} step={0.01} value={zoom}
            onChange={(e) => applyZoom(parseFloat(e.target.value))}
            className="flex-1 accent-emerald-500"
          />
        </div>

        <div className="mt-4 flex justify-end gap-2">
          <button
            onClick={onCancel}
            className="rounded-md border border-zinc-700 px-3 py-1.5 text-xs font-medium text-zinc-300 hover:bg-zinc-800"
          >
            Cancel
          </button>
          <button
            onClick={done}
            className="rounded-md bg-emerald-600 px-4 py-1.5 text-xs font-semibold text-white hover:bg-emerald-500"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
}

// ── Editable cell ──────────────────────────────────────────────────────────────
// Text that turns into an input on double-click; commits on Enter/blur, reverts on
// Escape. A single click runs onCellClick if given (price/ticker copy just that
// cell); otherwise it falls through to the row (which copies the whole row).
// `flash` briefly tints the cell green to confirm a single-cell copy.
function EditableCell({
  value, placeholder, mono, flash, onCommit, onCellClick,
}: {
  value: string; placeholder?: string; mono?: boolean; flash?: boolean;
  onCommit: (v: string) => void; onCellClick?: () => void;
}) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState('');
  // Seed the draft from the current value at the moment editing starts — no effect
  // syncing needed, since the draft only matters while the input is open.
  const startEdit = () => { setDraft(value); setEditing(true); };

  if (editing) {
    return (
      <input
        autoFocus
        value={draft}
        onClick={(e) => e.stopPropagation()}
        onChange={(e) => setDraft(e.target.value)}
        onBlur={() => { setEditing(false); if (draft !== value) onCommit(draft); }}
        onKeyDown={(e) => {
          if (e.key === 'Enter') { e.preventDefault(); (e.target as HTMLInputElement).blur(); }
          else if (e.key === 'Escape') { setDraft(value); setEditing(false); }
        }}
        className={`w-full select-text rounded bg-zinc-800 px-1.5 py-1 text-xs text-white outline-none ring-1 ring-emerald-500/60 ${mono ? 'font-mono tracking-wider' : ''}`}
      />
    );
  }
  const textColor = flash ? 'text-emerald-400 font-medium' : value ? 'text-zinc-100' : 'text-zinc-600';
  return (
    <span
      onClick={onCellClick ? (e) => { e.stopPropagation(); onCellClick(); } : undefined}
      onDoubleClick={(e) => { e.stopPropagation(); startEdit(); }}
      title={onCellClick ? 'Click to copy · double-click to edit' : 'Double-click to edit'}
      className={`block truncate rounded px-1.5 py-1 text-xs transition-colors ${textColor} ${mono ? 'font-mono tracking-wider' : ''} ${flash ? 'bg-emerald-600/15' : ''} ${onCellClick ? 'cursor-pointer' : ''}`}
    >
      {value || placeholder || '—'}
    </span>
  );
}

// ── Photo cell ─────────────────────────────────────────────────────────────────
function PhotoCell({
  img, onFile, onOpenCrop,
}: {
  img: ImgState | null;
  onFile: (file: File) => void;
  onOpenCrop: () => void;
}) {
  const [over, setOver] = useState(false);
  const inputRef = useRef<HTMLInputElement | null>(null);

  function pick(e: React.ChangeEvent<HTMLInputElement>) {
    const f = e.target.files?.[0];
    if (f) onFile(f);
    e.target.value = '';
  }
  function onDrop(e: React.DragEvent) {
    e.preventDefault(); e.stopPropagation(); setOver(false);
    const f = Array.from(e.dataTransfer.files).find((x) => x.type.startsWith('image/'));
    if (f) onFile(f);
  }

  return (
    <div
      onClick={(e) => e.stopPropagation()}
      onDragOver={(e) => { e.preventDefault(); setOver(true); }}
      onDragLeave={() => setOver(false)}
      onDrop={onDrop}
      className={`relative h-[72px] w-[72px] overflow-hidden rounded-md border transition-colors ${
        over ? 'border-emerald-500 bg-emerald-500/10' : 'border-zinc-700 bg-zinc-900'
      }`}
    >
      <input ref={inputRef} type="file" accept="image/*" hidden onChange={pick} />
      {img ? (
        <button onClick={onOpenCrop} className="group h-full w-full" title="Click to crop / reposition">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={img.thumb} alt="" className="h-full w-full object-cover" />
          <span className="absolute inset-0 flex items-center justify-center bg-black/0 text-[10px] font-medium text-white opacity-0 transition-opacity group-hover:bg-black/50 group-hover:opacity-100">
            Crop
          </span>
        </button>
      ) : (
        <button
          onClick={() => inputRef.current?.click()}
          className="flex h-full w-full flex-col items-center justify-center gap-0.5 text-zinc-600 hover:text-zinc-400"
          title="Drop or click to add a photo"
        >
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
            <rect x="3" y="3" width="18" height="18" rx="2" />
            <circle cx="8.5" cy="8.5" r="1.5" />
            <polyline points="21 15 16 10 5 21" />
          </svg>
          <span className="text-[8px] leading-none">Drop</span>
        </button>
      )}
    </div>
  );
}

// ── Main section ───────────────────────────────────────────────────────────────
export function PricerSection() {
  const [rows, setRows] = useState<Row[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [pasteText, setPasteText] = useState('');
  const [genLoading, setGenLoading] = useState(false);
  const [genError, setGenError] = useState<string | null>(null);
  const [genIds, setGenIds] = useState<Set<string>>(new Set()); // rows mid-generate
  // What was last copied + where, to flash the right thing: a whole-row copy tints
  // the row; a single-cell copy (price / ticker) flashes just that cell.
  const [copied, setCopied] = useState<{ id: string; scope: 'row' | 'price' | 'ticker' } | null>(null);
  const [downloading, setDownloading] = useState(false);
  const [crop, setCrop] = useState<{ rowId: string; src: string; nW: number; nH: number; crop: Crop } | null>(null);

  // Load once.
  useEffect(() => {
    try {
      const raw = localStorage.getItem(STORE_KEY);
      if (raw) setRows(JSON.parse(raw) as Row[]);
    } catch { /* ignore corrupt/blocked storage */ }
    setLoaded(true);
  }, []);

  // Persist (best-effort; on quota, drop full-res originals and keep thumbs).
  useEffect(() => {
    if (!loaded) return;
    try {
      localStorage.setItem(STORE_KEY, JSON.stringify(rows));
    } catch {
      try {
        const slim = rows.map((r) => (r.img ? { ...r, img: { ...r.img, src: '' } } : r));
        localStorage.setItem(STORE_KEY, JSON.stringify(slim));
      } catch { /* still too big — session-only */ }
    }
  }, [rows, loaded]);

  const patchRow = useCallback((id: string, patch: Partial<Row>) => {
    setRows((prev) => prev.map((r) => (r.id === id ? { ...r, ...patch } : r)));
  }, []);

  // ── Paste → rows ──────────────────────────────────────────────────────────────
  function addPasted() {
    const parsed = parsePaste(pasteText);
    if (parsed.length === 0) return;
    setRows((prev) => [...prev, ...parsed.map((p) => ({ id: newId(), name: p.name, price: p.price, ticker: '', img: null }))]);
    setPasteText('');
  }

  function addBlankRow() {
    setRows((prev) => [...prev, { id: newId(), name: '', price: '', ticker: '', img: null }]);
  }

  function removeRow(id: string) {
    setRows((prev) => prev.filter((r) => r.id !== id));
  }

  function clearAll() {
    if (rows.length && !confirm('Clear all rows?')) return;
    setRows([]);
  }

  // ── Tickers (DeepSeek) ──────────────────────────────────────────────────────────
  const generateFor = useCallback(async (targets: Row[]) => {
    const named = targets.filter((r) => r.name.trim());
    if (named.length === 0) return;
    setGenError(null);
    setGenLoading(true);
    setGenIds((s) => { const n = new Set(s); named.forEach((r) => n.add(r.id)); return n; });
    try {
      const res = await fetch('/api/ai/ticker', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ names: named.map((r) => r.name.trim()) }),
      });
      const data = await res.json().catch(() => ({})) as { tickers?: { ticker: string }[]; error?: string };
      if (!res.ok || data.error) throw new Error(data.error || `HTTP ${res.status}`);
      const tickers = data.tickers ?? [];
      setRows((prev) => prev.map((r) => {
        const pos = named.findIndex((n) => n.id === r.id);
        return pos >= 0 && tickers[pos] ? { ...r, ticker: tickers[pos].ticker } : r;
      }));
    } catch (e) {
      setGenError(e instanceof Error ? e.message : 'Ticker generation failed');
    } finally {
      setGenLoading(false);
      setGenIds((s) => { const n = new Set(s); named.forEach((r) => n.delete(r.id)); return n; });
    }
  }, []);

  function generateTickers() {
    const missing = rows.filter((r) => r.name.trim() && !r.ticker.trim());
    void generateFor(missing.length ? missing : rows);
  }

  // ── Photo handling ──────────────────────────────────────────────────────────────
  async function handleFile(rowId: string, file: File) {
    if (!file.type.startsWith('image/')) return;
    try {
      const src = await fileToDataURL(file);
      const im = await loadImage(src);
      const nW = im.naturalWidth, nH = im.naturalHeight;
      const size = Math.min(nW, nH);
      const c: Crop = { sx: (nW - size) / 2, sy: (nH - size) / 2, size }; // centered square
      const thumb = await cropToDataUrl(src, c, THUMB_PX);
      patchRow(rowId, { img: { src, nW, nH, crop: c, thumb } });
    } catch { /* unreadable image — ignore */ }
  }

  function openCrop(row: Row) {
    if (!row.img) return;
    const usingOriginal = !!row.img.src;
    setCrop({
      rowId: row.id,
      src: usingOriginal ? row.img.src : row.img.thumb,
      nW: usingOriginal ? row.img.nW : THUMB_PX,
      nH: usingOriginal ? row.img.nH : THUMB_PX,
      crop: usingOriginal ? row.img.crop : { sx: 0, sy: 0, size: THUMB_PX },
    });
  }

  async function applyCrop(nextCrop: Crop) {
    if (!crop) return;
    const target = crop;
    setCrop(null);
    try {
      const thumb = await cropToDataUrl(target.src, nextCrop, THUMB_PX);
      setRows((prev) => prev.map((r) => {
        if (r.id !== target.rowId || !r.img) return r;
        // Preserve the original src when we had it; otherwise the thumb is the
        // working source and the crop is relative to it.
        const usingOriginal = !!r.img.src;
        return {
          ...r,
          img: usingOriginal
            ? { ...r.img, crop: nextCrop, thumb }
            : { src: '', nW: THUMB_PX, nH: THUMB_PX, crop: { sx: 0, sy: 0, size: THUMB_PX }, thumb },
        };
      }));
    } catch { /* ignore */ }
  }

  // ── Copy + download ──────────────────────────────────────────────────────────────
  // Robust clipboard write: clear any native cell-text selection first so it can't
  // override what we put on the clipboard, then fall back to execCommand if the
  // async Clipboard API is blocked (insecure context / not focused).
  async function writeClipboard(text: string) {
    try { window.getSelection()?.removeAllRanges(); } catch { /* ignore */ }
    try {
      await navigator.clipboard.writeText(text);
      return;
    } catch { /* fall through to legacy path */ }
    try {
      const ta = document.createElement('textarea');
      ta.value = text;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      ta.remove();
    } catch { /* clipboard fully blocked — nothing more to do */ }
  }

  function flashCopy(id: string, scope: 'row' | 'price' | 'ticker') {
    setCopied({ id, scope });
    setTimeout(() => setCopied((c) => (c && c.id === id && c.scope === scope ? null : c)), 900);
  }

  // Whole row, tab-separated → pastes into Name / Price / Ticker columns of one
  // sheet row. Fired by clicking the row anywhere outside the price/ticker cells.
  async function copyRow(row: Row) {
    await writeClipboard([row.name, row.price, row.ticker].join('\t'));
    flashCopy(row.id, 'row');
  }

  // Single-cell copy — clicking the Price or Ticker cell copies just that value.
  async function copyCell(rowId: string, scope: 'price' | 'ticker', text: string) {
    await writeClipboard(text);
    flashCopy(rowId, scope);
  }

  async function downloadRow(row: Row) {
    if (!row.img) return;
    const usingOriginal = !!row.img.src;
    const source = usingOriginal ? row.img.src : row.img.thumb;
    const c = usingOriginal ? row.img.crop : { sx: 0, sy: 0, size: THUMB_PX };
    const out = Math.min(4096, Math.max(1, Math.round(c.size)));
    const blob = await cropToBlob(source, c, out);
    triggerDownload(blob, `${safeFile(row.ticker || row.name)}.png`);
  }

  async function downloadAll() {
    const withImg = rows.filter((r) => r.img);
    if (withImg.length === 0) return;
    setDownloading(true);
    try {
      for (const r of withImg) {
        await downloadRow(r);
        await sleep(250); // stagger so the browser doesn't drop concurrent saves
      }
    } finally {
      setDownloading(false);
    }
  }

  const photoCount = rows.filter((r) => r.img).length;

  return (
    <div className="flex h-screen flex-col bg-black text-white">
      {/* Header */}
      <div className="shrink-0 border-b border-zinc-900 px-6 py-4">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-lg font-semibold">Pricer</h1>
            <p className="text-xs text-zinc-500">
              Paste names + prices, generate tickers, attach cropped photos. Click a row to copy it.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={generateTickers}
              disabled={genLoading || rows.every((r) => !r.name.trim())}
              className="flex items-center gap-1.5 rounded-md bg-emerald-600 px-3 py-1.5 text-xs font-semibold text-white hover:bg-emerald-500 disabled:cursor-not-allowed disabled:opacity-40"
            >
              {genLoading ? (
                <span className="h-3 w-3 animate-spin rounded-full border-2 border-white/40 border-t-white" />
              ) : (
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M12 2l2.2 5.8L20 10l-5.8 2.2L12 18l-2.2-5.8L4 10l5.8-2.2z" />
                </svg>
              )}
              Generate tickers
            </button>
            <button
              onClick={downloadAll}
              disabled={downloading || photoCount === 0}
              className="flex items-center gap-1.5 rounded-md border border-zinc-700 px-3 py-1.5 text-xs font-medium text-zinc-200 hover:bg-zinc-800 disabled:cursor-not-allowed disabled:opacity-40"
            >
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              {downloading ? 'Downloading…' : `Download all${photoCount ? ` (${photoCount})` : ''}`}
            </button>
            <button
              onClick={clearAll}
              disabled={rows.length === 0}
              className="rounded-md border border-zinc-800 px-3 py-1.5 text-xs font-medium text-zinc-400 hover:bg-zinc-900 hover:text-red-400 disabled:cursor-not-allowed disabled:opacity-40"
            >
              Clear
            </button>
          </div>
        </div>

        {/* Paste box */}
        <div className="mt-3 flex gap-2">
          <textarea
            value={pasteText}
            onChange={(e) => setPasteText(e.target.value)}
            onKeyDown={(e) => { if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) { e.preventDefault(); addPasted(); } }}
            placeholder={'Paste from your sheet — one per line:\nLeBron James\t12.50\nTaylor Swift\t8.20'}
            rows={2}
            className="flex-1 resize-none rounded-md border border-zinc-800 bg-zinc-950 px-3 py-2 text-xs text-zinc-200 placeholder:text-zinc-600 focus:border-zinc-600 focus:outline-none"
          />
          <div className="flex flex-col gap-1.5">
            <button
              onClick={addPasted}
              disabled={!pasteText.trim()}
              className="rounded-md bg-zinc-100 px-4 py-1.5 text-xs font-semibold text-black hover:bg-white disabled:cursor-not-allowed disabled:opacity-40"
            >
              Add rows
            </button>
            <button
              onClick={addBlankRow}
              className="rounded-md border border-zinc-800 px-4 py-1.5 text-xs font-medium text-zinc-400 hover:bg-zinc-900"
            >
              + Blank
            </button>
          </div>
        </div>
        {genError && <p className="mt-2 text-xs text-red-400">Ticker error: {genError}</p>}
      </div>

      {/* Table */}
      <div className="min-h-0 flex-1 overflow-auto px-6 py-4">
        {rows.length === 0 ? (
          <div className="flex h-full flex-col items-center justify-center gap-2 text-center">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl border border-zinc-800 bg-zinc-900">
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" className="text-zinc-600">
                <path d="M20.59 13.41 13.42 20.6a2 2 0 0 1-2.83 0L3 13V3h10l7.59 7.59a2 2 0 0 1 0 2.82z" />
                <circle cx="7.5" cy="7.5" r="1.5" />
              </svg>
            </div>
            <p className="text-sm font-medium text-zinc-400">No rows yet</p>
            <p className="text-xs text-zinc-600">Paste a Name + Price block above to get started.</p>
          </div>
        ) : (
          <div className="overflow-hidden rounded-lg border border-zinc-900">
            {/* head */}
            <div className="grid grid-cols-[88px_84px_36px_1fr_120px_150px] items-center gap-2 border-b border-zinc-900 bg-zinc-950 px-3 py-2 text-[10px] font-semibold uppercase tracking-wider text-zinc-500">
              <span>Photo</span>
              <span>Actions</span>
              <span>#</span>
              <span>Name</span>
              <span>Price</span>
              <span>Ticker</span>
            </div>
            {/* rows */}
            {rows.map((row, i) => (
              <div
                key={row.id}
                onClick={() => copyRow(row)}
                title="Click to copy this row"
                className={`grid cursor-pointer select-none grid-cols-[88px_84px_36px_1fr_120px_150px] items-center gap-2 border-b border-zinc-900 px-3 py-2 transition-colors last:border-b-0 ${
                  copied?.id === row.id && copied.scope === 'row' ? 'bg-emerald-600/15' : 'hover:bg-zinc-900/60'
                }`}
              >
                {/* photo */}
                <PhotoCell
                  img={row.img}
                  onFile={(f) => handleFile(row.id, f)}
                  onOpenCrop={() => openCrop(row)}
                />

                {/* actions */}
                <div className="flex items-center justify-start gap-1" onClick={(e) => e.stopPropagation()}>
                  <button
                    onClick={() => downloadRow(row)}
                    disabled={!row.img}
                    title="Download cropped PNG"
                    className="rounded p-1.5 text-zinc-500 hover:bg-zinc-800 hover:text-zinc-100 disabled:opacity-30"
                  >
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                      <polyline points="7 10 12 15 17 10" />
                      <line x1="12" y1="15" x2="12" y2="3" />
                    </svg>
                  </button>
                  <button
                    onClick={() => removeRow(row.id)}
                    title="Delete row"
                    className="rounded p-1.5 text-zinc-600 hover:bg-zinc-800 hover:text-red-400"
                  >
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <polyline points="3 6 5 6 21 6" />
                      <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
                    </svg>
                  </button>
                </div>

                <span className="text-[11px] tabular-nums text-zinc-600">
                  {copied?.id === row.id && copied.scope === 'row'
                    ? <span className="font-semibold text-emerald-400">✓</span>
                    : i + 1}
                </span>

                <EditableCell value={row.name} placeholder="name" onCommit={(v) => patchRow(row.id, { name: v })} />
                <EditableCell
                  value={row.price}
                  placeholder="price"
                  flash={copied?.id === row.id && copied.scope === 'price'}
                  onCellClick={() => copyCell(row.id, 'price', row.price)}
                  onCommit={(v) => patchRow(row.id, { price: v })}
                />

                {/* ticker + per-row regen */}
                <div className="flex items-center gap-1" onClick={(e) => e.stopPropagation()}>
                  <div className="min-w-0 flex-1">
                    <EditableCell
                      value={row.ticker}
                      placeholder="—"
                      mono
                      flash={copied?.id === row.id && copied.scope === 'ticker'}
                      onCellClick={() => copyCell(row.id, 'ticker', row.ticker)}
                      onCommit={(v) => patchRow(row.id, { ticker: v.trim() })}
                    />
                  </div>
                  <button
                    onClick={() => generateFor([row])}
                    disabled={!row.name.trim() || genIds.has(row.id)}
                    title="Generate ticker"
                    className="shrink-0 rounded p-1 text-zinc-600 hover:bg-zinc-800 hover:text-emerald-400 disabled:opacity-30"
                  >
                    {genIds.has(row.id) ? (
                      <span className="block h-3 w-3 animate-spin rounded-full border-2 border-zinc-600 border-t-emerald-400" />
                    ) : (
                      <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M21 2v6h-6" /><path d="M3 12a9 9 0 0 1 15-6.7L21 8" />
                        <path d="M3 22v-6h6" /><path d="M21 12a9 9 0 0 1-15 6.7L3 16" />
                      </svg>
                    )}
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {crop && (
        <CropModal
          source={{ src: crop.src, nW: crop.nW, nH: crop.nH, crop: crop.crop }}
          onDone={applyCrop}
          onCancel={() => setCrop(null)}
        />
      )}
    </div>
  );
}
